### ISSUE TITLE
2.0 will not install - unmet deps

### ISSUE THREAD

**Issue by chrisdlangton** [meanie/express-error-handling#1]
├── meanie-express-error-handling@2.0.0 
├── UNMET PEER DEPENDENCY meanie-express-github-service@^2.0.1
└── UNMET PEER DEPENDENCY meanie-express-raven-service@^1.0.0

**Comment by adamreisnz** [comment]
@chrisdlangton have you updated your `package.json` to include those packages?

The github service is actually no longer required, but the raven service is needed for the Sentry error tracking middleware. I've released a patch to remove the github service from the dependencies.

**Comment by adamreisnz** [comment]
In fact, I've made it an optional dep in case you don't use the Sentry error middleware, so it should install ok now even without the dep.
